name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: make install
    - name: refactor
      run: make refactor
    - name: test
      run: make test
    - name: testint
      run: make testint
