name: Makefile CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Run Setup
      run: make setup

    - name: Run tests
      run: make test

    - name: Run linting
      run: make lint

    - name: Run type checking
      run: make type-check

    - name: Run format check
      run: make format
