name: Makefile CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: make setup
      run: make setup
    - name: make refactor
      run: make refactor
    - name: demo
      if: github.ref == 'refs/heads/main'
      run: bash demo.sh zo
